services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 6006:6006
    tty: true
    stdin_open: true
    volumes:
      - ./src:/home/node/todo
  db:
    image: postgres:14.2
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - 5432:5432